### ISSUE TITLE
coveralls側にデータが送られない

### ISSUE THREAD

**Issue by tsub** [tsub/awesome_events#25]
coverallsのトークンを.coveralls.ymlで指定しておかないと、CI側からcoverallsにデータを送信できないため、coverallsのビルド内容が更新されない

**Comment by tsub** [comment]
github上のコードを調べてみると、ENVで拾ってる人とそのままトークン置いてる人がいる模様

https://github.com/search?q=repo_token&type=Code&utf8=%E2%9C%93

**Comment by a-know** [comment]
CI の中でトークンが必要になるんなら、 CircleCI の Environment Variables に設定すればいいんじゃないかな？

**Comment by tsub** [comment]
> CI の中でトークンが必要になるんなら、 CircleCI の Environment Variables に設定すればいいんじゃないかな？

あ、それを考えてました！ 😀 
ちょっと後で対応しようかなと思ってissueだけ作ってたところです

**Comment by tsub** [comment]
ずっと放置していて多分やらないのでクローズ。
